import { createRequire } from 'node:module'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import pluginVue from 'eslint-plugin-vue'
import { defineConfigWithVueTs, vueTsConfigs } from '@vue/eslint-config-typescript'

// @vue/eslint-config-prettier is CommonJS — use createRequire to interop in .mjs
const require = createRequire(import.meta.url)
const skipFormatting = require('@vue/eslint-config-prettier/skip-formatting')

// Load auto-import globals generated by unplugin-auto-import (eslintrc: { enabled: true })
const __filename = fileURLToPath(import.meta.url)
const __dir = dirname(__filename)
const autoImportGlobals = JSON.parse(
  readFileSync(resolve(__dir, '.eslintrc-auto-import.json'), 'utf-8'),
).globals

export default defineConfigWithVueTs(
  // Files to lint
  {
    name: 'app/files-to-lint',
    files: ['**/*.{ts,mts,vue}'],
  },
  // Files to ignore
  {
    name: 'app/files-to-ignore',
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      '**/*.d.ts',
      'src/types/auto-imports.d.ts',
      'src/types/components.d.ts',
    ],
  },
  // Vue essential rules
  pluginVue.configs['flat/essential'],
  // TypeScript rules (vue-ts aware)
  vueTsConfigs.recommended,
  // Disable formatting rules (Prettier handles that)
  skipFormatting,
  // Inject auto-import globals so ESLint knows about ref/computed/ElMessage etc.
  {
    name: 'app/auto-import-globals',
    languageOptions: {
      globals: Object.fromEntries(
        Object.entries(autoImportGlobals).map(([k]) => [k, 'readonly']),
      ),
    },
  },
  // Project-level rule overrides
  {
    name: 'app/rule-overrides',
    rules: {
      // vue/multi-word-component-names: our page components (e.g. App.vue) are single-word —
      // suppress for this project rather than mass-rename
      'vue/multi-word-component-names': 'off',

      // @typescript-eslint/no-explicit-any: existing code uses `any` in some DTOs/utils;
      // demote to warn to avoid blocking CI while keeping visibility
      '@typescript-eslint/no-explicit-any': 'warn',

      // Allow unused vars prefixed with _ (common pattern for intentional ignores)
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
)
